### ISSUE TITLE
tests navigation components

### ISSUE THREAD

**Issue by Faust1-2was-Aneo** [aneoconsulting/ArmoniK.Admin.GUI#666]
- [x] navigation #667
- [x] add-external-service-dialog #669 
- [x] edit-external-service-dialog #670
- [x] form-external-service-dialog #671 
- [x] manage-external-service-dialog #672
- [x] theme-selector #674
