### ISSUE TITLE
applications component and services tests

### ISSUE THREAD

**Issue by Faust1-2was-Aneo** [aneoconsulting/ArmoniK.Admin.GUI#717]
- [x] applications component #587
- [x] applications grpc service #718
- [x] applications index service #710
- [x] applications filter service #716
