### ISSUE TITLE
tasks component and services tests 

### ISSUE THREAD

**Issue by fdewas-aneo** [aneoconsulting/ArmoniK.Admin.GUI#719]
- [x] index component
- [x] tasks index service #697
- [x] tasks filters service #673
- [x] tasks grpc service
- [x] tasks statuses service #657
