### ISSUE TITLE
test dashboard components

### ISSUE THREAD

**Issue by Faust1-2was-Aneo** [aneoconsulting/ArmoniK.Admin.GUI#722]
- [x] add line dialog component #725
- [x] add statuses group dialog component #726
- [x] edit name line dialog component #727
- [x] edit status-group-dialog component #728
- [x] form name line component #724
- [x] form statuses group component #730
- [x] line component #731
- [x] manage groups dialog component #732
- [x] reorganize lines dialog component #733
- [x] split lines dialog component #734
- [x] statuses group card component #735
